[workspace]
members = [
    "app",
    "crates/utils/*",
    "crates/viewers/*",
]
package.version = "0.1.0"
package.edition = "2024"
package.rust-version = "1.88"
resolver = "3"

[workspace.dependencies]
log = "0.4.27"
thiserror = "2.0.12"
anyhow = "1.0.98"
regex = "1.11.1"
image = "0.25.6"
flate2 = "1.1.2"
serde = { version = "1.0.219", features = ["derive"] }
