[package]
name = "universal-explorer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bitflags = "2.6.0"
clap = { version = "4.5.11", features = ["derive"] }
eframe = "0.28.1"
egui = "0.28.1"
env_logger = { version = "0.11.5", features = ["auto-color", "humantime"] }
# TEMP FIX: Fix dynamic linking with `zune-jpeg` crate
# https://github.com/etemesi254/zune-image/commit/5846e3cd7ee786fcc4714133509db166aeb069bb
# https://github.com/image-rs/image/pull/2209
image = { git = "https://github.com/Murad-Awad/image", branch = "upgrade-zune" }
# image = "0.25.2"
rayon = "1.10.0"
regex = "1.10.5"
rfd = "0.14.1"
uuid = { version = "1.10.0", features = ["v7"] }
