[package]
name = "util_python"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
util_general = { path = "../general" }
log.workspace = true
thiserror.workspace = true
anyhow.workspace = true
flate2.workspace = true
serde.workspace = true
paste = "1.0.15"