[package]
name = "util_archive"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
util_general = { path = "../general" }
util_vfs = { path = "../vfs" }
util_codec = { path = "../codec" }
log.workspace = true
thiserror.workspace = true
anyhow.workspace = true
