
name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    permissions: write-all

    strategy:
      fail-fast: false
      matrix:
        os: [ windows-x86_64, linux-x86_64 ]
        include:
          - os: linux-x86_64
            target: x86_64-unknown-linux-musl
            artifact_name: universal-explorer
            asset_name: universal-explorer_linux_x86_64
          - os: windows-x86_64
            target: x86_64-pc-windows-gnu
            artifact_name: universal-explorer.exe
            asset_name: universal-explorer_win_x86_64.exe
            linker_package: gcc-mingw-w64-x86-64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cache-${{ matrix.os }}-release

      - name: Setup Rust
        run: rustup toolchain install stable --profile minimal --target ${{ matrix.target }} --no-self-update

      # TODO: Cache linker installation.
      - name: Install linker
        if: matrix.linker_package != null
        run: sudo apt-get install -y ${{ matrix.linker_package }}

      - name: Build project
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}


